NotebookTask/NotebookTask/Controllers/UserNoteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NotebookTask.Bll.Services.Interfaces;
using NotebookTask.Common.Models;
using NotebookTask.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace NotebookTask.Controllers
{
    [Authorize]
    public class UserNoteController : Controller
    {
        private readonly INoteService noteService;
        private readonly ICategoryService categoryService;
        private readonly IUserService userService;
        private readonly IImageService imageService;
        private readonly IHttpContextAccessor httpContextAccessor;

        public UserNoteController(INoteService noteService, ICategoryService categoryService, IImageService imageService,
            IUserService userService, IHttpContextAccessor httpContextAccessor)
        {
            this.imageService = imageService;
            this.categoryService = categoryService;
            this.userService = userService;
            this.noteService = noteService;
            this.httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult List(string categoryName)
        {
            SelectList categories = new SelectList(categoryService.GetAll().ToList(), "Id", "CategoryName");
            ViewBag.Categories = categories;
            var listNoteViewModels = new List<ListNoteViewModel>();
            var userEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimsIdentity.DefaultNameClaimType).Value;
            var id = userService.GetByEmail(userEmail).Id;
            ListNoteViewModel listNoteViewModel;
            var userNotes = noteService.GetByUserId(id);

            foreach (var note in userNotes)
            {
                listNoteViewModel = new ListNoteViewModel
                {
                    Id = note.Id,
                    Category = categoryService.GetById(note.CategoryId is null ? 0 : (int)note.CategoryId).CategoryName,
                    User = userService.GetById(note.UserId).UserLogin,
                    Image = imageService.GetById(note.ImageId is null ? 0 : (int)note.ImageId).ImageData,
                    Name = note.NoteName,
                    CreatedDate = note.NoteCreatedDate,
                    Description = note.NoteDescription
                };

                listNoteViewModels.Add(listNoteViewModel);
            }

            if (categoryName is null)
            {
                return View(listNoteViewModels);
            }

            var notes = listNoteViewModels.Where(x => x.Category.Equals(categoryName));

            return View(notes);
        }

        [HttpPost]
        public IActionResult List(int? categoryId)
        {
            if (categoryId is null)
            {
                return RedirectToAction(nameof(List));
            }

            string categoryName = categoryService.GetById((int)categoryId).CategoryName;

            return RedirectToAction(nameof(List), new { categoryName = categoryName });
        }

        [HttpPost]
        public IActionResult Create(CreateNoteViewModel model)
        {
            var userEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimsIdentity.DefaultNameClaimType).Value;
            var id = userService.GetByEmail(userEmail).Id;

            string imageData = UploadImage(model.ImageData);

            Image image = new Image
            {
                ImageData = imageData,
            };

            imageService.Create(image);

            Note note = new Note
            {
                UserId = id,
                CategoryId = model.Category,
                NoteName = model.Name,
                NoteDescription = model.Description,
                ImageId = imageService.GetIdByImageData(imageData),
                NoteReferenceId = 0,
                NoteCreatedDate = DateTime.Now
            };

            noteService.Create(note);

            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        private string UploadImage(IFormFile imageData)
        {
            return (imageData != null) ? imageService.UploadImage(imageData) : null;
        }

        [HttpGet]
        public IActionResult Create()
        {
            SelectList categories = new SelectList(categoryService.GetAll().ToList(), "Id", "CategoryName");
            ViewBag.Categories = categories;

            return View();
        }

        public IActionResult Delete(int id)
        {
            noteService.Delete(id);

            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public IActionResult Edit()
        {
            SelectList categories = new SelectList(categoryService.GetAll().ToList(), "Id", "CategoryName");
            ViewBag.Categories = categories;

            return View();
        }

        [HttpPost]
        public IActionResult Edit(int id, EditNoteViewModel model)
        {
            var userEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimsIdentity.DefaultNameClaimType).Value;
            var UserId = userService.GetByEmail(userEmail).Id;
            string imageData = string.Empty;

            if (model.ImageData != null)
            {
                if (model.ImageData.FileName != noteService.GetImageDataById(id))
                {
                    imageData = UploadImage(model.ImageData);

                    Image image = new Image
                    {
                        ImageData = imageData,
                    };

                    imageService.Create(image);
                }
            }

            Note note = new Note
            {
                Id = id,
                CategoryId = model.Category,
                ImageId = imageService.GetIdByImageData(imageData),
                NoteCreatedDate = model.CreatedDate,
                NoteDescription = model.Description,
                NoteName = model.Name,
                UserId = UserId,
                NoteReferenceId = 0
            };

            noteService.Update(id, note);

            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public IActionResult Search(string text, DateTime? begin, DateTime? end)
        {
            ViewData["GetText"] = text;

            var listNoteViewModels = new List<ListNoteViewModel>();
            var userEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimsIdentity.DefaultNameClaimType).Value;
            var id = userService.GetByEmail(userEmail).Id;
            ListNoteViewModel listNoteViewModel;
            var userNotes = noteService.GetByUserId(id);

            foreach (var note in userNotes)
            {
                listNoteViewModel = new ListNoteViewModel
                {
                    Id = note.Id,
                    Category = categoryService.GetById(note.CategoryId is null ? 0 : (int)note.CategoryId).CategoryName,
                    User = userService.GetById(note.UserId).UserLogin,
                    Image = imageService.GetById(note.ImageId is null ? 0 : (int)note.ImageId).ImageData,
                    Name = note.NoteName,
                    CreatedDate = note.NoteCreatedDate,
                    Description = note.NoteDescription
                };

                listNoteViewModels.Add(listNoteViewModel);
            }

            if (!string.IsNullOrWhiteSpace(text))
            {
                var notesWithText = from x in listNoteViewModels where x.Name.Contains(text) || x.Category.Contains(text) select x;

                return View(notesWithText);
            }

            if (!(begin is null || end is null))
            {
                var notes = from x in listNoteViewModels where x.CreatedDate >= begin && x.CreatedDate <= end select x;

                return View(notes);
            }

            return View(listNoteViewModels);
        }

        [HttpGet]
        public IActionResult Search()
        {
            var listNoteViewModels = new List<ListNoteViewModel>();
            var userEmail = httpContextAccessor.HttpContext.User.FindFirst(ClaimsIdentity.DefaultNameClaimType).Value;
            var id = userService.GetByEmail(userEmail).Id;
            ListNoteViewModel listNoteViewModel;
            var userNotes = noteService.GetByUserId(id);

            foreach (var note in userNotes)
            {
                listNoteViewModel = new ListNoteViewModel
                {
                    Id = note.Id,
                    Category = categoryService.GetById(note.CategoryId is null ? 0 : (int)note.CategoryId).CategoryName,
                    User = userService.GetById(note.UserId).UserLogin,
                    Image = imageService.GetById(note.ImageId is null ? 0 : (int)note.ImageId).ImageData,
                    Name = note.NoteName,
                    CreatedDate = note.NoteCreatedDate,
                    Description = note.NoteDescription
                };

                listNoteViewModels.Add(listNoteViewModel);
            }

            return View(listNoteViewModels);
        }
    }
}

NotebookTask/NotebookTask/Views/UserNote/Create.cshtml
@model NotebookTask.ViewModels.CreateNoteViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create note</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                @Html.DropDownList("Category", ViewBag.Categories as SelectList, "Please select Category")
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageData" class="control-label"></label>
                <input asp-for="ImageData" class="form-control" />
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NotebookTask/NotebookTask/Views/UserNote/Edit.cshtml
@model NotebookTask.ViewModels.EditNoteViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit note</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                @Html.DropDownList("Category", ViewBag.Categories as SelectList, "Please select Category")
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageData" class="control-label"></label>
                <input asp-for="ImageData" class="form-control" />
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NotebookTask/NotebookTask/Views/UserNote/List.cshtml
@model IEnumerable<NotebookTask.ViewModels.ListNoteViewModel>

@{
    ViewData["Title"] = "List";
}

<h1>Notes</h1>

<p>
    <a asp-action="Create">Create New</a> |
    <a asp-action="Search">Search page</a>
</p>

<form asp-action="List" asp-controller="UserNote">
    <p>
        @Html.DropDownList("categoryId", ViewBag.Categories as SelectList, "Select category")
        <input type="submit" value="Show notes by category" class="btn btn-primary" />
        <a asp-action="List">Show all notes</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @if (item.Image is null || item.Image.Equals(string.Empty))
                    {
                        <p>-</p>
                    }
                    else
                    {
                        <img src="~/Images/@item.Image" width="60" height="60" asp-append-version="true" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

NotebookTask/NotebookTask/Views/UserNote/Search.cshtml
@model IEnumerable<NotebookTask.ViewModels.ListNoteViewModel>

@{
    ViewData["Title"] = "Search";
}

<h1>Search</h1>

<p>
    <a asp-action="List">Back to notes</a>
</p>

<form asp-action="Search" asp-controller="UserNote">
    <p>
        <input type="search" placeholder="Enter note name or category" value="@ViewData["GetText"]" name="text"/>
        <input type="submit" value="Search" class="btn btn-primary" />
        <a asp-action="Search">Show all notes</a>
    </p>
</form>

<form asp-action="Search" asp-controller="UserNote">
    <p>
        <input type="datetime-local" name="begin"/>
        <input  type="datetime-local" name="end"/>
        <input type="submit" value="Search in datetime range" class="btn btn-primary" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @if (item.Image is null || item.Image.Equals(string.Empty))
                    {
                        <p>-</p>
                    }
                    else
                    {
                        <img src="~/Images/@item.Image" width="60" height="60" asp-append-version="true" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
            </tr>
        }
    </tbody>
</table>